### ISSUE TITLE
Longer variable names

### ISSUE THREAD

**Issue by Blaza** [dkahle/mpoly#9]
First of all, thanks for a very useful package!

I ran into an error during my work. I am programmatically creating mpolys which can have one or more variables, so I index them as x1, x2, ... When I only have a univariate polynomial, I end up having only x1, so a polynomial like "x1^2 + 5 x1 + 6", and arithmetic and stuff works fine. The problem comes when you use the as.function function.  I get an error:
```
Error in chartr(vars(x), ".", mpoly_string) : 'old' is longer than 'new'
```
Having taken a quick look at the code, I think the problem is in [this line](https://github.com/dkahle/mpoly/blob/bdcb749ee0ac0f46aef659add2e048852bccced7/R/as.function.mpoly.R#L65), where you're using `chartr` to replace variable name with `.`, so because my variable name has two chars, it runs into an error. 

I think this can be easily fixed by using e.g. `gsub` instead of `chartr`.

Or is this expected behaviour?

**Comment by dkahle** [comment]
Think I got it, thanks!
